<?php

	/*
		TODO:: QUERY TO FIND ALL LIBRARY WHERE ARE ACTIVE MEMBER
	*/
	
	/*
		TODO:: QUERY TO FIND ALL LIBRARY WHERE ARE INACTIVE MEMBER
	*/
	
	/*
		TODO:: QUERY TO FIND ALL LIBRARY WHERE REQUESTED TO BE MEMBER
	*/

?>