<?php

	/*
		TODO:: QUERY TO FIND ALL BOOKS THAT ARE ISSUED AND YET NOT SUBMITTED
	*/
	
	/*
		TODO:: QUERY TO FIND ALL BOOKS IN CONNECTED LIBRARIES THAT ARE NOT ISSUED
	*/
	
	/*
		TODO:: QUERY TO FIND ALL BOOKS THAT ARE ISSUED AND SUBMITTED IN PAST
	*/

?>